version: '3.3'
services: 
  authentication:
    build:
      context: .
      dockerfile: ./authentication/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./authentication:/app
    depends_on: 
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Astra
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 8080:3306