version: '3.8'
services: 
  authentication:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on: 
      - db

  db:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - 5432:5432